dtagent:
  container_name: "dtagent"
  hostname: "docker-dtagent"
  image: "dynatrace/agent:6.5"
  environment:
    DT_AGENT_NAME: "dtagent"
  volumes:
    - /dynatrace
    - "/tmp/log/dynatrace/agents/dtagent:/dynatrace/log/agent"